import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedFrame758531190Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedArrowLeft2Widget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedWFButtonWidget16.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedWFButtonWidget15.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedFrame273Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedOrderId24252Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/Generated\$20Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedOrderId24252Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedChatWidget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedFrame758531082Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedWFButtonWidget17.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget17.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedRectangle411Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedFrame758531186Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax52widget/generated/GeneratedFrame758531070Widget2.dart';

/* Frame iPhone 13 Pro Max - 52
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax52Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget2(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 31.0,
                              child: GeneratedOrderId24252Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 32.0,
                              child: GeneratedFrame758531082Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 431.0,
                              right: null,
                              bottom: null,
                              width: 224.0,
                              height: 44.0,
                              child: GeneratedFrame758531070Widget2(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 442.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedChatWidget14(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 189.0,
                              child: GeneratedFrame758531186Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 194.0,
                              right: null,
                              bottom: null,
                              width: 166.0,
                              height: 26.0,
                              child: GeneratedOrderId24252Widget3(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 194.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 29.0,
                              child: Generated$20Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 495.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 88.0,
                              child: GeneratedFrame758531190Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 663.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget15(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle411Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 44.0,
                              child: GeneratedWFButtonWidget16(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 44.0,
                              child: GeneratedWFButtonWidget17(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget17(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
