import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedFrame758531146Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedLabelWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedWearethesolutionforyourhomecleanlinessWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedObsessivecompulsivedisorderrafikiWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax70widget/generated/GeneratedWFButtonWidget1.dart';

/* Frame iPhone 13 Pro Max - 70
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax70Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 16.0,
                              child: GeneratedFrame758531146Widget1(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 29.0,
                              child: GeneratedLabelWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 513.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 53.0,
                              child:
                                  GeneratedWearethesolutionforyourhomecleanlinessWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 194.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 283.00006103515625,
                              child:
                                  GeneratedObsessivecompulsivedisorderrafikiWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
