import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530969Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedServiceWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530971Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530966Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530973Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget12.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530931Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530961Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530968Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530974Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530972Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530967Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax15widget/generated/GeneratedFrame758530970Widget.dart';

/* Frame iPhone 13 Pro Max - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 85.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 40.0,
                              child: GeneratedFrame758530961Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 76.0,
                              child: GeneratedFrame758530931Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 586.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 76.0,
                              child: GeneratedFrame758530972Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 682.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 76.0,
                              child: GeneratedFrame758530973Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 778.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 76.0,
                              child: GeneratedFrame758530974Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 442.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 29.0,
                              child: GeneratedServiceWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530966Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530967Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530968Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530969Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530970Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 389.0,
                              right: null,
                              bottom: null,
                              width: 379.2842712402344,
                              height: 28.284271240234375,
                              child: GeneratedFrame758530971Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget12(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
