import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedFrame758531215Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedFrame273Widget11.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedRectangle403Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedRectangle404Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedWFButtonWidget24.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedRectangle402Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget31.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedArrowLeft2Widget32.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedServiceSettingWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax63widget/generated/GeneratedFrame758531216Widget.dart';

/* Frame iPhone 13 Pro Max - 63
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax63Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget11(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget32(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 26.0,
                              child: GeneratedServiceSettingWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 39.0,
                              child: GeneratedFrame758531215Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 298.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle402Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 159.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 39.0,
                              child: GeneratedFrame758531216Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle404Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 138.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle403Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 772.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedWFButtonWidget24(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget31(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
