import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedArrowLeftCircleWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedChoosethetypeofyouraccountWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedRectangle21Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedWFButtonWidget32.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedRectangle20Widget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedFrame758531246Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedLOGOWidget9.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedWorkerWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedServiceManWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedEmojionev1flagforarmeniaWidget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/Generated45Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedRectangle430Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget44.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax69widget/generated/GeneratedTypeofAccountWidget1.dart';

/* Frame iPhone 13 Pro Max - 69
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax69Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget9(),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget10(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget10(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 29.0,
                              child: Generated45Widget6(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 26.0,
                              child: GeneratedTypeofAccountWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 26.0,
                              child:
                                  GeneratedChoosethetypeofyouraccountWidget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 201.0,
                              child: GeneratedFrame758531246Widget1(),
                            ),
                            Positioned(
                              left: 303.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 2.0,
                              child: GeneratedRectangle21Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget32(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget44(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 31.0,
                              child: GeneratedServiceManWidget(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedWorkerWidget1(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 201.0,
                              child: GeneratedRectangle430Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
