import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedLabelWidget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedHouserestylingcuateWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedWFButtonWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedWearethesolutionforyourhomecleanlinessWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax89widget/generated/GeneratedFrame758531146Widget3.dart';

/* Frame iPhone 13 Pro Max - 89
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax89Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 16.0,
                              child: GeneratedFrame758531146Widget3(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget3(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 29.0,
                              child: GeneratedLabelWidget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 513.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 53.0,
                              child:
                                  GeneratedWearethesolutionforyourhomecleanlinessWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 250.84963989257812,
                              child: GeneratedHouserestylingcuateWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
