import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531250Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531254Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedBookmarkWidget20.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531238Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedEllipse85Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame273Widget16.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531251Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531237Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531137Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget40.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame240Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedNotificationWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame249Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531231Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531253Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame238Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedOurPromoWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedVouchersWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531252Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedSeemoreWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame243Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758530950Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame242Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame239Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758531138Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax119widget/generated/GeneratedFrame758530961Widget2.dart';

/* Frame iPhone 13 Pro Max - 119
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax119Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1173.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1173.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedNotificationWidget10(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBookmarkWidget20(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531231Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 29.0,
                              child: GeneratedVouchersWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame238Widget1(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame239Widget1(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame240Widget1(),
                            ),
                            Positioned(
                              left: 337.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame242Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 716.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame249Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 784.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530950Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1108.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget16(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531237Widget(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531238Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 947.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531252Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531253Widget(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531254Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget40(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 26.0,
                              child: GeneratedOurPromoWidget(),
                            ),
                            Positioned(
                              left: 351.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 26.0,
                              child: GeneratedSeemoreWidget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame243Widget1(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 96.0,
                              child: GeneratedFrame758531137Widget1(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 96.0,
                              child: GeneratedFrame758531138Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 40.0,
                              child: GeneratedFrame758530961Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 182.0,
                              child: GeneratedFrame758531250Widget(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 179.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 182.0,
                              child: GeneratedFrame758531251Widget(),
                            ),
                            Positioned(
                              left: 168.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedEllipse85Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
