import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531225Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle417Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedSuggestedLanguageWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle423Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle420Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle416Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle421Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531220Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget29.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531222Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle419Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle415Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531221Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle418Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531223Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedRectangle422Widget18.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531227Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531219Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531218Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531224Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedOthersLanguageWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax118widget/generated/GeneratedFrame758531226Widget.dart';

/* Frame iPhone 13 Pro Max - 118
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax118Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 125.0,
                              right: null,
                              bottom: null,
                              width: 164.0,
                              height: 26.0,
                              child: GeneratedSuggestedLanguageWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 303.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 26.0,
                              child: GeneratedOthersLanguageWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle415Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle416Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 77.0,
                              right: null,
                              bottom: null,
                              width: 301.0,
                              height: 24.0,
                              child: GeneratedFrame758531218Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget29(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531219Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531220Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle417Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531221Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle418Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 416.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531222Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 525.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle419Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531223Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle420Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 546.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531224Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 655.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle421Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531225Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 720.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle422Widget18(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 676.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531226Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle423Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531227Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
