import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Vector 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVector6Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 0.00,
            b: -1.00,
            c: 1.00,
            d: 0.00,
            child: Opacity(
              opacity: 0.4000000059604645,
              child: Container(
                width: 182.0,
                height: 88.0,
                child: SvgWidget(painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M76.7068 18.3434C36.3609 16.9003 9.97594 11.1764 0 15.9683L0 88L182 88L182 7.14121C160.322 8.26679 114.346 -6.03782 114.346 3.02277C114.346 7.7178 111.249 19.5789 76.7068 18.3434Z')
                    ..setLinearGradient(
                      startX: 91.0,
                      startY: -6.225833762405087e-13,
                      endX: 91.0,
                      endY: 87.99999999999937,
                      colors: [
                        Color.fromARGB(255, 255, 255, 255),
                        Color.fromARGB(0, 255, 255, 255)
                      ],
                      colorStops: [0.0, 0.4088999330997467],
                    ),
                ]),
              ),
            )));
  }
}
