import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse4Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame24Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse2Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame758530959Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedNotificationWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse3Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedUnsplash8Hwow5VfUWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedRectangle398Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame758531170Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedRectangle400Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse5Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame758531172Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedRectangle19Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedJaneCooperWidget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedWFButtonWidget20.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/Generated\$201hrWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget24.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedBookmarkWidget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedArrowLeft2Widget22.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedAboutMeWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitAtatcurs.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse86Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedYounghousekeeperfemalewithcleaningsupply1Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedUnsplash8Hwow5VfUWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedAvailalbeWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame758530958Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedFrame758530954Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedRectangle422Widget16.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse8Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedRectangle399Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax32widget/generated/GeneratedEllipse7Widget5.dart';

/* Frame iPhone 13 Pro Max - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1074.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1074.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 253.0,
                              child: GeneratedRectangle422Widget16(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedArrowLeft2Widget22(),
                            ),
                            Positioned(
                              left: 453.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedNotificationWidget1(),
                            ),
                            Positioned(
                              left: 481.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedFrameWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 24.0,
                              child: GeneratedFrame758530954Widget(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse86Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 398.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 22.0,
                              child: GeneratedAboutMeWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 54.0,
                              child:
                                  GeneratedLoremipsumdolorsitametconsecteturadipiscingelitAtatcurs(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 385.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle19Widget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 494.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle398Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 949.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle399Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 978.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle400Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 40.0,
                              child: GeneratedFrame758530958Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 788.0,
                              right: null,
                              bottom: null,
                              width: 531.0,
                              height: 145.0,
                              child: GeneratedFrame758531172Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 958.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 12.0,
                              child: GeneratedFrame758530959Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 349.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 29.0,
                              child: Generated$201hrWidget10(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 995.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget20(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 541.0,
                              right: null,
                              bottom: null,
                              width: 157.0,
                              height: 157.0,
                              child: GeneratedUnsplash8Hwow5VfUWidget(),
                            ),
                            Positioned(
                              left: 223.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 159.0,
                              child: GeneratedUnsplash8Hwow5VfUWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 507.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 20.0,
                              child: GeneratedFrame758531170Widget(),
                            ),
                            Positioned(
                              left: 137.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 155.0,
                              height: 209.0,
                              child:
                                  GeneratedYounghousekeeperfemalewithcleaningsupply1Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget24(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 273.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 26.0,
                              child: GeneratedJaneCooperWidget4(),
                            ),
                            Positioned(
                              left: 384.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedBookmarkWidget8(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 32.0,
                              child: GeneratedFrame24Widget2(),
                            ),
                            Positioned(
                              left: 348.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedNotificationWidget3(),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedFrameWidget1(),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 17.0,
                              child: GeneratedAvailalbeWidget(),
                            ),
                            Positioned(
                              left: 174.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse2Widget4(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse3Widget5(),
                            ),
                            Positioned(
                              left: 210.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse4Widget4(),
                            ),
                            Positioned(
                              left: 228.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse5Widget4(),
                            ),
                            Positioned(
                              left: 246.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse7Widget5(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 708.0,
                              right: null,
                              bottom: null,
                              width: 4.0,
                              height: 4.0,
                              child: GeneratedEllipse8Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
