import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatedgroup160widget2/generated/GeneratedRectangle422Widget11.dart';
import 'package:flutterapp/klapmeapp/generatedgroup160widget2/generated/GeneratedYounghousekeeperfemalewithcleaningsupply1Widget3.dart';

/* Group Group 160
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup160Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 70.0,
      height: 88.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 88.0,
              child: GeneratedRectangle422Widget11(),
            ),
            Positioned(
              left: 8.0,
              top: 8.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 72.0,
              child:
                  GeneratedYounghousekeeperfemalewithcleaningsupply1Widget3(),
            )
          ]),
    ));
  }
}
