import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedFrame758531196Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedFinishedWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedArrowLeft2Widget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedFrame273Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedRectangle19Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedFrame758531198Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedOrdersWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedFrame758531197Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedInProgressWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedRectangle20Widget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax51widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget18.dart';

/* Frame iPhone 13 Pro Max - 51
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax51Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget10(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 89.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 29.0,
                              child: GeneratedOrdersWidget5(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 26.0,
                              child: GeneratedInProgressWidget3(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 29.0,
                              child: GeneratedFinishedWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget6(),
                            ),
                            Positioned(
                              left: 223.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget4(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 204.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 193.0,
                              child: GeneratedFrame758531196Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 193.0,
                              child: GeneratedFrame758531197Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 622.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 193.0,
                              child: GeneratedFrame758531198Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget18(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
