import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531137Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedOurPromoWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531253Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531138Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame239Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedNotificationWidget12.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531252Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531237Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedBookmarkWidget30.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame243Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame240Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedSeemoreWidget9.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedEllipse85Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531231Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame238Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758530961Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531238Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531251Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758530950Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame242Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame273Widget17.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame249Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedVouchersWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget47.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531250Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax67widget/generated/GeneratedFrame758531254Widget1.dart';

/* Frame iPhone 13 Pro Max - 67
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax67Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1173.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1173.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedNotificationWidget12(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBookmarkWidget30(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531231Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 29.0,
                              child: GeneratedVouchersWidget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame238Widget2(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame239Widget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame240Widget2(),
                            ),
                            Positioned(
                              left: 337.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame242Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 716.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame249Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 784.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530950Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1108.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget17(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531237Widget1(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531238Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 947.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531252Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531253Widget1(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531254Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget47(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 26.0,
                              child: GeneratedOurPromoWidget1(),
                            ),
                            Positioned(
                              left: 351.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 26.0,
                              child: GeneratedSeemoreWidget9(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame243Widget2(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 96.0,
                              child: GeneratedFrame758531137Widget2(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 96.0,
                              child: GeneratedFrame758531138Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 40.0,
                              child: GeneratedFrame758530961Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 182.0,
                              child: GeneratedFrame758531250Widget1(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 179.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 182.0,
                              child: GeneratedFrame758531251Widget1(),
                            ),
                            Positioned(
                              left: 168.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedEllipse85Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
