import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedArrowLeft2Widget34.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedSendWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedGroup95Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget32.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedFrame758531164Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedFrame39Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedFrame758530928Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedGroup96Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax25widget/generated/GeneratedJaneCooperCleaningWidget2.dart';

/* Frame iPhone 13 Pro Max - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget34(),
                            ),
                            Positioned(
                              left: 78.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 26.0,
                              child: GeneratedJaneCooperCleaningWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle29Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 51.0,
                              child: GeneratedGroup95Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 51.0,
                              child: GeneratedGroup96Widget(),
                            ),
                            Positioned(
                              left: 181.0,
                              top: 155.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 20.0,
                              child: GeneratedFrame39Widget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 853.0,
                              right: null,
                              bottom: null,
                              width: 339.0,
                              height: 41.0,
                              child: GeneratedFrame758531164Widget(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 861.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedSendWidget(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 42.0,
                              child: GeneratedFrame758530928Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget32(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
