import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedGroup160Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedFrame758531039Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedJaneCooperWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedChatWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedArrowLeft2Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedWFButtonWidget13.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedLocationWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedRectangle388Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedFrame758531162Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedMyOrdersWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedRectangle19Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedHouseCleaningWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedArrowDown2Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget15.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedLocationWidget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedMapsicleMapWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedRectangle20Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedOrderId24252Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedFrame275Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedFrame758531038Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedFinishedWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedCancelledWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax45widget/generated/GeneratedInProgressWidget1.dart';

/* Frame iPhone 13 Pro Max - 45
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax45Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget4(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 26.0,
                              child: GeneratedMyOrdersWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 26.0,
                              child: GeneratedInProgressWidget1(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 29.0,
                              child: GeneratedFinishedWidget1(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 29.0,
                              child: GeneratedCancelledWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget4(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget6(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 205.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 544.0,
                              child: GeneratedRectangle388Widget5(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 17.0,
                              child: GeneratedFrame758531162Widget1(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 19.0,
                              child: GeneratedHouseCleaningWidget1(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 21.0,
                              child: GeneratedJaneCooperWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 88.0,
                              child: GeneratedGroup160Widget1(),
                            ),
                            Positioned(
                              left: 320.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedChatWidget10(),
                            ),
                            Positioned(
                              left: 368.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedArrowDown2Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame275Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 289.0,
                              child: GeneratedMapsicleMapWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 653.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 44.0,
                              child: GeneratedFrame758531038Widget(),
                            ),
                            Positioned(
                              left: 294.0,
                              top: 665.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 17.0,
                              child: GeneratedOrderId24252Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 629.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 16.0,
                              child: GeneratedFrame758531039Widget(),
                            ),
                            Positioned(
                              left: 125.5,
                              top: 387.5,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 133.5,
                              child: GeneratedVector2Widget(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedLocationWidget4(),
                            ),
                            Positioned(
                              left: 273.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedLocationWidget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget13(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget15(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
