import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame38Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedGroup98Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame30Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedArrowLeft2Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedLocationWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame36Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame24Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedRecentsearchesWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame29Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame25Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame758530961Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame31Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget13.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame34Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/Generated2464RoyalLnMesaNewJersey45463Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame37Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame33Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedPopularsearchWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame28Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedSearchbycategoryWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame32Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax33widget/generated/GeneratedFrame26Widget.dart';

/* Frame iPhone 13 Pro Max - 33
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax33Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedLocationWidget(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 277.0,
                              height: 19.0,
                              child:
                                  Generated2464RoyalLnMesaNewJersey45463Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 81.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 16.0,
                              child: GeneratedGroup98Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 40.0,
                              child: GeneratedFrame758530961Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 213.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 26.0,
                              child: GeneratedRecentsearchesWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 369.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 26.0,
                              child: GeneratedSearchbycategoryWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 541.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 26.0,
                              child: GeneratedPopularsearchWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 253.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 32.0,
                              child: GeneratedFrame24Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 40.0,
                              child: GeneratedFrame29Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 40.0,
                              child: GeneratedFrame32Widget(),
                            ),
                            Positioned(
                              left: 146.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 103.0,
                              height: 40.0,
                              child: GeneratedFrame30Widget(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 40.0,
                              child: GeneratedFrame33Widget(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 40.0,
                              child: GeneratedFrame31Widget(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 253.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 32.0,
                              child: GeneratedFrame25Widget(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 253.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 32.0,
                              child: GeneratedFrame26Widget(),
                            ),
                            Positioned(
                              left: 274.0,
                              top: 253.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 32.0,
                              child: GeneratedFrame27Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 301.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 32.0,
                              child: GeneratedFrame28Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 581.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 32.0,
                              child: GeneratedFrame34Widget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 581.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 32.0,
                              child: GeneratedFrame35Widget(),
                            ),
                            Positioned(
                              left: 193.0,
                              top: 581.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 32.0,
                              child: GeneratedFrame36Widget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 581.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 32.0,
                              child: GeneratedFrame37Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 629.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 32.0,
                              child: GeneratedFrame38Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
