import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame758531102Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame267Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame229Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame228Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame264Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame225Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame263Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame266Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle8Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget21.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame265Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame272Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedFrame271Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax27widget/generated/GeneratedRectangle25Widget1.dart';

/* Frame iPhone 13 Pro Max - 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 206.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle21Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle22Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame264Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle23Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame265Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle24Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame266Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 554.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle25Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 484.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame267Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle8Widget7(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 47.0,
                              child: GeneratedFrame225Widget2(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 47.0,
                              child: GeneratedFrame229Widget6(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 47.0,
                              child: GeneratedFrame272Widget5(),
                            ),
                            Positioned(
                              left: 266.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 47.0,
                              child: GeneratedFrame228Widget6(),
                            ),
                            Positioned(
                              left: 186.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 47.0,
                              child: GeneratedFrame271Widget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 36.0,
                              child: GeneratedFrame758531102Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget21(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame263Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
