import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated6Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated25Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated3Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedLOGOWidget1.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated4Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedDontreceivecodeResendWidget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedBarsStatusBarsiPhoneLightWidget5.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedWFButtonWidget5.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedEptimerWidget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedPleaseenterthe6digitverificationcodesenttoat629129Widge.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedEmojionev1flagforarmeniaWidget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated1Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedArrowLeftCircleWidget2.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated2Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated5Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/Generated0020SecWidget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/klapmeapp/generatedmobileverificationwidget/generated/GeneratedMobileVerificationWidget.dart';

/* Frame Mobile verification
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMobileverificationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget1(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 4.0,
                              child: GeneratedRectangle20Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget2(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 29.0,
                              child: Generated25Widget(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 216.0,
                              height: 26.0,
                              child: GeneratedMobileVerificationWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 50.0,
                              child:
                                  GeneratedPleaseenterthe6digitverificationcodesenttoat629129Widge(),
                            ),
                            Positioned(
                              left: 193.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 66.0,
                              height: 20.0,
                              child: Generated0020SecWidget(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedEptimerWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 574.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget5(),
                            ),
                            Positioned(
                              left: 123.0,
                              top: 524.0,
                              right: null,
                              bottom: null,
                              width: 183.0,
                              height: 20.0,
                              child: GeneratedDontreceivecodeResendWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle39Widget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle40Widget(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle44Widget(),
                            ),
                            Positioned(
                              left: 356.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle41Widget(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle42Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle43Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated6Widget(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 34.0,
                              child: Generated5Widget(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated4Widget(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated3Widget(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 34.0,
                              child: Generated2Widget(),
                            ),
                            Positioned(
                              left: 373.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 17.0,
                              height: 34.0,
                              child: Generated1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
