import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedRectangle20Widget9.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/Generated45Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedArrowLeftCircleWidget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedWFButtonWidget31.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedLOGOWidget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget43.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedEmojionev1flagforarmeniaWidget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedImageWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedTypeofAccountWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedImageWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax7widget/generated/GeneratedChoosethetypeofyouraccountWidget.dart';

/* Frame iPhone 13 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget8(),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget6(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget9(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget8(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 29.0,
                              child: Generated45Widget5(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 26.0,
                              child: GeneratedTypeofAccountWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 26.0,
                              child:
                                  GeneratedChoosethetypeofyouraccountWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 316.0,
                              right: null,
                              bottom: null,
                              width: 378.0,
                              height: 169.0,
                              child: GeneratedImageWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 169.0,
                              child: GeneratedImageWidget2(),
                            ),
                            Positioned(
                              left: 303.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 2.0,
                              child: GeneratedRectangle21Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 718.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget31(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget43(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
