import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531186Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedRectangle388Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget16.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531183Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531182Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531188Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedWFButtonWidget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531187Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFinishedWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531189Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame273Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedRectangle410Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax49widget/generated/GeneratedFrame758531184Widget.dart';

/* Frame iPhone 13 Pro Max - 49
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax49Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 36.0,
                              child: GeneratedFrame758531182Widget(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 29.0,
                              child: GeneratedFinishedWidget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 37.0,
                              child: GeneratedFrame758531183Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 655.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget14(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 534.0,
                              child: GeneratedRectangle388Widget6(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 189.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 32.0,
                              child: GeneratedFrame758531184Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 24.0,
                              child: GeneratedFrame758531187Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 233.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 1.0,
                              child: GeneratedRectangle410Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 483.0,
                              right: null,
                              bottom: null,
                              width: 332.0,
                              height: 44.0,
                              child: GeneratedFrame758531188Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 189.0,
                              child: GeneratedFrame758531186Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 547.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 88.0,
                              child: GeneratedFrame758531189Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget16(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
