import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedFrame758531029Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedFrame758531030Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedFrame758531037Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedMapsicleMapWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget37.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedVector3Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedServiceStatusWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedLocationWidget35.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedLocationWidget34.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/Generated\$20Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedFrame758531026Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedWFButtonWidget27.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax39widget/generated/GeneratedFrame758531176Widget.dart';

/* Frame iPhone 13 Pro Max - 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 78.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 36.0,
                              child: GeneratedFrame758531030Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 71.0,
                              child: GeneratedFrame758531037Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 235.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 211.0,
                              child: GeneratedMapsicleMapWidget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 462.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 16.0,
                              child: GeneratedFrame758531026Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 76.0,
                              child: GeneratedFrame758531029Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 581.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 19.0,
                              child: GeneratedServiceStatusWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 184.0,
                              height: 175.0,
                              child: GeneratedFrame758531176Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 809.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget27(),
                            ),
                            Positioned(
                              left: 373.0,
                              top: 518.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 24.0,
                              child: Generated$20Widget4(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 285.5,
                              right: null,
                              bottom: null,
                              width: 201.5,
                              height: 67.5,
                              child: GeneratedVector3Widget(),
                            ),
                            Positioned(
                              left: 301.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedLocationWidget34(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 335.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedLocationWidget35(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget37(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
