import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame254Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedAllServiceWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame758530930Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget41.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedRectangle392Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame251Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame252Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedRectangle391Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame250Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedFrame253Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax21widget/generated/GeneratedCategoryWidget.dart';

/* Frame iPhone 13 Pro Max - 21
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 427.0,
                              height: 872.0,
                              child: GeneratedRectangle391Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 102.0,
                              right: null,
                              bottom: null,
                              width: 83.0,
                              height: 26.0,
                              child: GeneratedAllServiceWidget(),
                            ),
                            Positioned(
                              left: 198.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 2.0,
                              child: GeneratedRectangle392Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 148.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame250Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame251Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame252Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame253Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 545.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame254Widget(),
                            ),
                            Positioned(
                              left: 364.0,
                              top: 113.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 18.0,
                              child: GeneratedFrame758530930Widget(),
                            ),
                            Positioned(
                              left: 368.0,
                              top: 116.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedCategoryWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget41(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
