import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedFrame758530927Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedGroup95Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedFrame758531211Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedFrame758530928Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedGroup96Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedFrame39Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax60widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget33.dart';

/* Frame iPhone 13 Pro Max - 60
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax60Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 132.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle29Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 189.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 51.0,
                              child: GeneratedGroup95Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 252.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 51.0,
                              child: GeneratedGroup96Widget1(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 20.0,
                              child: GeneratedFrame39Widget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 853.0,
                              right: null,
                              bottom: null,
                              width: 383.0,
                              height: 41.0,
                              child: GeneratedFrame758530927Widget(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 315.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 42.0,
                              child: GeneratedFrame758530928Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 316.0,
                              height: 36.0,
                              child: GeneratedFrame758531211Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget33(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
