import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedVouchersWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame249Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedEllipse3Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame242Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531245Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531163Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame243Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedPopularServiceWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531138Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531244Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531246Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedServiceCategoryWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame239Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget39.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame273Widget15.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame238Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedImageWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedEllipse4Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531249Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531247Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531133Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedWFButtonWidget29.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedEllipse5Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531248Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame240Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedFrame758531137Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax66widget/generated/GeneratedEllipse2Widget5.dart';

/* Frame iPhone 13 Pro Max - 66
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax66Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1170.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1170.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 24.0,
                              child: GeneratedFrame758531249Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 128.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 140.0,
                              child: GeneratedFrame758531163Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 128.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 140.0,
                              child: GeneratedImageWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 26.0,
                              child: GeneratedServiceCategoryWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 595.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 29.0,
                              child: GeneratedVouchersWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame238Widget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame239Widget(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame240Widget(),
                            ),
                            Positioned(
                              left: 337.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame242Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 475.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 96.0,
                              child: GeneratedFrame243Widget(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 475.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 96.0,
                              child: GeneratedFrame758531137Widget(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 475.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 96.0,
                              child: GeneratedFrame758531138Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 639.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame249Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 707.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 26.0,
                              child: GeneratedPopularServiceWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 870.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531133Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1086.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget15(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 32.0,
                              child: GeneratedWFButtonWidget29(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget39(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse2Widget5(),
                            ),
                            Positioned(
                              left: 184.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse3Widget7(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse4Widget5(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse5Widget5(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedFrame758531248Widget(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 914.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531244Widget(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 751.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531246Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 914.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531245Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 751.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 99.0,
                              child: GeneratedFrame758531247Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
