import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget34.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle416Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531107Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531108Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle414Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531110Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle419Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle415Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531112Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531111Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531106Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle410Widget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame758531109Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle418Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedRectangle417Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax57widget/generated/GeneratedFrame229Widget9.dart';

/* Frame iPhone 13 Pro Max - 57
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax57Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 106.0,
                              child: GeneratedRectangle414Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 265.0,
                              height: 36.0,
                              child: GeneratedFrame758531106Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 66.0,
                              child: GeneratedFrame758531107Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 263.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 66.0,
                              child: GeneratedFrame758531108Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle410Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle419Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 349.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle415Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 370.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 66.0,
                              child: GeneratedFrame758531109Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 456.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle416Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 477.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 66.0,
                              child: GeneratedFrame758531110Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle417Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 66.0,
                              child: GeneratedFrame758531111Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle418Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame758531112Widget1(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 859.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 47.0,
                              child: GeneratedFrame229Widget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget34(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
