import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531152Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531038Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531154Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedYouhave9bookmarkWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531153Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531049Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedFrame758531151Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax44widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget23.dart';

/* Frame iPhone 13 Pro Max - 44
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax44Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 257.0,
                              height: 36.0,
                              child: GeneratedFrame758531038Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 32.0,
                              child: GeneratedFrame758531049Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 166.0,
                              height: 26.0,
                              child: GeneratedYouhave9bookmarkWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 231.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531151Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531152Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 487.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531153Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 615.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531154Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget23(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
