import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedFrame758531260Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedRectangle20Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedFrame758531130Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedYourPhotoSelfieWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedEmojionev1flagforarmeniaWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedIDVerificationWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedToverificationyouridweneedyoutouploadyourphotoselfieand.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/Generated55Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedLOGOWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax6widget/generated/GeneratedArrowLeftCircleWidget6.dart';

/* Frame iPhone 13 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget3(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget6(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 29.0,
                              child: Generated55Widget(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 26.0,
                              child: GeneratedIDVerificationWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 50.0,
                              child:
                                  GeneratedToverificationyouridweneedyoutouploadyourphotoselfieand(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 26.0,
                              child: GeneratedYourPhotoSelfieWidget(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 80.0,
                              child: GeneratedFrame758531260Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 537.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 287.0,
                              child: GeneratedFrame758531130Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 2.0,
                              child: GeneratedRectangle25Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
