import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758531023Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedWFButtonWidget23.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedLabelWidget28.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedIconRightWrapperWidget19.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758531022Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758531025Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedIconLeftWrapperWidget18.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758531024Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758531021Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedFrame758530975Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax37widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget27.dart';

/* Frame iPhone 13 Pro Max - 37
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax37Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 36.0,
                              child: GeneratedFrame758530975Widget2(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 24.0,
                              child: GeneratedIconLeftWrapperWidget18(),
                            ),
                            Positioned(
                              left: 183.5,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 29.0,
                              child: GeneratedLabelWidget28(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 24.0,
                              child: GeneratedIconRightWrapperWidget19(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 124.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531021Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 208.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531022Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 292.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531023Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 376.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531024Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531025Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget23(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget27(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
