import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedLabelWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedPipelineWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedFrame758531146Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedWFButtonWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedCharacter1Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedBackgroundsimpleWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedWearethesolutionforyourhomecleanlinessWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedBackgroundcompleteWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax88widget/generated/GeneratedFloorWidget.dart';

/* Frame iPhone 13 Pro Max - 88
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax88Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 16.0,
                              child: GeneratedFrame758531146Widget2(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget2(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 29.0,
                              child: GeneratedLabelWidget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 513.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 53.0,
                              child:
                                  GeneratedWearethesolutionforyourhomecleanlinessWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget2(),
                            ),
                            Positioned(
                              left: 39.31396484375,
                              top: 155.77197265625,
                              right: null,
                              bottom: null,
                              width: 364.68603515625,
                              height: 218.09078979492188,
                              child: GeneratedBackgroundcompleteWidget1(),
                            ),
                            Positioned(
                              left: 49.7873649597168,
                              top: 151.22329711914062,
                              right: null,
                              bottom: null,
                              width: 226.24041748046875,
                              height: 149.20297241210938,
                              child: GeneratedBackgroundsimpleWidget1(),
                            ),
                            Positioned(
                              left: 28.37548828125,
                              top: 466.651611328125,
                              right: null,
                              bottom: null,
                              width: 375.62451171875,
                              height: 0.374221533536911,
                              child: GeneratedFloorWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 245.428466796875,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 221.60447692871094,
                              child: GeneratedPipelineWidget(),
                            ),
                            Positioned(
                              left: 35.28369903564453,
                              top: 278.4110107421875,
                              right: null,
                              bottom: null,
                              width: 188.08474731445312,
                              height: 198.5890350341797,
                              child: GeneratedCharacter1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
