import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget26.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedIconLeftWrapperWidget16.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758531173Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedWFButtonWidget22.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758530975Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758530992Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758530995Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedIconRightWrapperWidget17.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedLabelWidget26.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758531174Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedRectangle404Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758531005Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax35widget/generated/GeneratedFrame758530997Widget.dart';

/* Frame iPhone 13 Pro Max - 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax35Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 36.0,
                              child: GeneratedFrame758530975Widget1(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 24.0,
                              child: GeneratedIconLeftWrapperWidget16(),
                            ),
                            Positioned(
                              left: 183.5,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 29.0,
                              child: GeneratedLabelWidget26(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 24.0,
                              child: GeneratedIconRightWrapperWidget17(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle404Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 131.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 97.0,
                              child: GeneratedFrame758530992Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 180.0,
                              child: GeneratedFrame758530995Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 612.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 118.0,
                              child: GeneratedFrame758531005Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 64.0,
                              child: GeneratedFrame758531174Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 834.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget22(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 541.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 55.0,
                              child: GeneratedFrame758530997Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 261.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 68.0,
                              child: GeneratedFrame758531173Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget26(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
