import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame274Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758531165Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530937Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530935Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530939Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758531168Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530936Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758531166Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530942Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530934Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedAccountSettingsWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530933Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedRectangle428Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget28.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530941Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax28widget/generated/GeneratedFrame758530940Widget.dart';

/* Frame iPhone 13 Pro Max - 28
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax28Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 173.0,
                              child: GeneratedRectangle428Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 894.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle28Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame274Widget4(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 73.0,
                              child: GeneratedFrame758531168Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 136.0,
                              height: 21.0,
                              child: GeneratedAccountSettingsWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530939Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 650.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530940Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 698.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530941Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 771.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530942Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 576.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle30Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle31Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530934Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530933Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 384.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530935Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 432.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530936Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530937Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531166Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531165Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget28(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
