import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/Generated35Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedTogiveyoubetterexperienceweneedtoknowyourpersonalinform.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedPersonalInformationWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedWFButtonWidget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame13Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame6Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedEmojionev1flagforarmeniaWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedRectangle19Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedLOGOWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax8widget/generated/GeneratedArrowLeftCircleWidget4.dart';

/* Frame iPhone 13 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget2(),
                            ),
                            Positioned(
                              left: 371.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget1(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 4.0,
                              child: GeneratedRectangle20Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget4(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 29.0,
                              child: Generated35Widget(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 239.0,
                              height: 26.0,
                              child: GeneratedPersonalInformationWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 484.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame6Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame7Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame9Widget(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame15Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame10Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 628.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame12Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 700.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame13Widget(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame11Widget(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 48.0,
                              child: GeneratedFrame8Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 60.0,
                              child: GeneratedWFButtonWidget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 234.0,
                              height: 16.0,
                              child: GeneratedFrame14Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 50.0,
                              child:
                                  GeneratedTogiveyoubetterexperienceweneedtoknowyourpersonalinform(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
