import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedRectangle19Widget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFinishedWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedArrowLeft2Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame758531149Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedInProgressWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame275Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame758531150Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedCancelledWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame758531148Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame758531147Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedMyOrdersWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedFrame758531145Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax16widget/generated/GeneratedRectangle20Widget5.dart';

/* Frame iPhone 13 Pro Max - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget2(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 86.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 26.0,
                              child: GeneratedMyOrdersWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 26.0,
                              child: GeneratedInProgressWidget(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 29.0,
                              child: GeneratedFinishedWidget(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 29.0,
                              child: GeneratedCancelledWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget5(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531145Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531147Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 455.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531148Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 583.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531149Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 112.0,
                              child: GeneratedFrame758531150Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame275Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget14(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
