import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame138Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame758531045Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedArrowLeft2Widget42.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget38.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedUserRatingsWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame758531046Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame758531044Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame758531048Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax42widget/generated/GeneratedFrame758531049Widget1.dart';

/* Frame iPhone 13 Pro Max - 42
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax42Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 958.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 257.0,
                              child: GeneratedFrame138Widget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 573.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 115.0,
                              child: GeneratedFrame758531045Widget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 708.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 115.0,
                              child: GeneratedFrame758531046Widget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 115.0,
                              child: GeneratedFrame758531049Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child: GeneratedArrowLeft2Widget42(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 26.0,
                              child: GeneratedUserRatingsWidget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 132.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 92.0,
                              child: GeneratedFrame758531044Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 378.0,
                              height: 32.0,
                              child: GeneratedFrame758531048Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget38(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
