import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget20.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame758531204Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedMaskGroupWidget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame273Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame758531211Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame758531205Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame758531209Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedFrame758531210Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax54widget/generated/GeneratedRectangle22Widget.dart';

/* Frame iPhone 13 Pro Max - 54
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax54Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget7(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 36.0,
                              child: GeneratedFrame758531209Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 206.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle21Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1.0,
                              child: GeneratedRectangle22Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget20(),
                            ),
                            Positioned(
                              left: 359.0,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 39.0,
                              child: GeneratedFrame758531205Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 54.0,
                              child: GeneratedMaskGroupWidget6(),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 183.0,
                              height: 46.0,
                              child: GeneratedFrame758531204Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame758531210Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedFrame758531211Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
