import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget45.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/Generated45Widget7.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedChoosethetypeofyouraccountWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedWFButtonWidget33.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedLOGOWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedRectangle20Widget11.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedTypeofAccountWidget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedArrowLeftCircleWidget12.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedEmojionev1flagforarmeniaWidget8.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedRectangle21Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax87widget/generated/GeneratedFrame758531257Widget.dart';

/* Frame iPhone 13 Pro Max - 87
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax87Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget10(),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget8(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 3.0,
                              child: GeneratedRectangle20Widget11(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget12(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 29.0,
                              child: Generated45Widget7(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 26.0,
                              child: GeneratedTypeofAccountWidget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 26.0,
                              child:
                                  GeneratedChoosethetypeofyouraccountWidget2(),
                            ),
                            Positioned(
                              left: 303.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 2.0,
                              child: GeneratedRectangle21Widget4(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget33(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget45(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 169.0,
                              child: GeneratedFrame758531257Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
