import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame273Widget9.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758530942Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531122Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedRectangle429Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedRectangle30Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531120Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531214Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531117Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531123Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758530943Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget30.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531115Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531115Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531112Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531116Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758530935Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedCameraWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedAccountSettingsWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531121Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758530933Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax59widget/generated/GeneratedFrame758531115Widget.dart';

/* Frame iPhone 13 Pro Max - 59
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax59Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget9(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 136.0,
                              height: 21.0,
                              child: GeneratedAccountSettingsWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 237.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530943Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 277.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531121Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 317.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531123Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 786.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530942Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle30Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 769.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle31Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 432.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530933Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758530935Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531112Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 392.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531122Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 21.0,
                              child: GeneratedFrame758531120Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531115Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531115Widget1(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 649.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531115Widget2(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 689.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531116Widget1(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 729.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 24.0,
                              child: GeneratedFrame758531117Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 176.0,
                              child: GeneratedRectangle429Widget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedCameraWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 72.0,
                              child: GeneratedFrame758531214Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget30(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
