import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedWFButtonWidget4.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedEnterYourNumberPhoneWidget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedCreateaccounttocontinueWidget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedLOGOWidget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedFrame39Widget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedFrame6Widget1.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedBarsStatusBarsiPhoneLightWidget4.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedEmojionev1flagforascensionislandWidget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedFrame758531159Widget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedArrowLeftCircleWidget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/Generated15Widget.dart';
import 'package:flutterapp/klapmeapp/generatedregitrationwidget/generated/GeneratedRegistrationWidget.dart';

/* Frame Regitration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegitrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame758531159Widget(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 428.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 17.0,
                              child: GeneratedEnterYourNumberPhoneWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 48.0,
                              child: GeneratedFrame6Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 134.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedArrowLeftCircleWidget(),
                            ),
                            Positioned(
                              left: 387.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 29.0,
                              child: Generated15Widget(),
                            ),
                            Positioned(
                              left: 146.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 29.0,
                              child: GeneratedRegistrationWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 183.0,
                              height: 26.0,
                              child: GeneratedCreateaccounttocontinueWidget(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 19.0,
                              child: GeneratedFrame39Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 54.0,
                              child: GeneratedWFButtonWidget4(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child:
                                  GeneratedEmojionev1flagforascensionislandWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 428.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 15.0,
                              child: GeneratedFrame6Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget4(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 2.0,
                              child: GeneratedRectangle19Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
