import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/Generated5Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/Generated3Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle389Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedWFButtonWidget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/Generated4Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedDontreceivecodeResendWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/Generated2Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedPleaseenterthe6digitverificationcodesentviaSMSat629129W.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedFrame758531132Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedMobileVerificationWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax18widget/generated/Generated6Widget1.dart';

/* Frame iPhone 13 Pro Max - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 216.0,
                              height: 26.0,
                              child: GeneratedMobileVerificationWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 50.0,
                              child:
                                  GeneratedPleaseenterthe6digitverificationcodesentviaSMSat629129W(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 20.0,
                              child: GeneratedFrame758531132Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 60.0,
                              child: GeneratedWFButtonWidget6(),
                            ),
                            Positioned(
                              left: 123.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 183.0,
                              height: 20.0,
                              child: GeneratedDontreceivecodeResendWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle39Widget1(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle40Widget1(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle44Widget1(),
                            ),
                            Positioned(
                              left: 356.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle41Widget1(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 407.0,
                              right: null,
                              bottom: null,
                              width: 1.0,
                              height: 24.0,
                              child: GeneratedRectangle389Widget(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle42Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 2.0,
                              child: GeneratedRectangle43Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated6Widget1(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 34.0,
                              child: Generated5Widget1(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated4Widget1(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 34.0,
                              child: Generated3Widget1(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 34.0,
                              child: Generated2Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
