import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedLocationWidget29.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/Generated13MilesWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedFrame758531055Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget36.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedJaneCooperHouseWidget5.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedVector7Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedRectangle408Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedMapsicleMapWidget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedMaskGroupWidget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedWFButtonWidget25.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedRectangle403Widget4.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedFrame758531068Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedWFButtonWidget26.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedLocationWidget28.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedCleaningWidget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedFrame758531060Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedFrame273Widget14.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax46widget/generated/GeneratedFrame758531059Widget.dart';

/* Frame iPhone 13 Pro Max - 46
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax46Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget14(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 769.0,
                              child: GeneratedMapsicleMapWidget4(),
                            ),
                            Positioned(
                              left: 325.0,
                              top: 211.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedLocationWidget28(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 250.5,
                              right: null,
                              bottom: null,
                              width: 245.0,
                              height: 43.5,
                              child: GeneratedVector7Widget2(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedLocationWidget29(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 257.0,
                              child: GeneratedRectangle408Widget(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 574.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 23.0,
                              child: GeneratedFrame758531055Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 665.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 1.0,
                              child: GeneratedRectangle403Widget4(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 297.0,
                              height: 36.0,
                              child: GeneratedFrame758531059Widget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 22.0,
                              child: GeneratedCleaningWidget14(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 682.0,
                              right: null,
                              bottom: null,
                              width: 166.0,
                              height: 21.0,
                              child: GeneratedJaneCooperHouseWidget5(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedMaskGroupWidget14(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 260.0,
                              height: 16.0,
                              child: GeneratedFrame758531060Widget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 758.0,
                              right: null,
                              bottom: null,
                              width: 103.0,
                              height: 16.0,
                              child: GeneratedFrame758531068Widget(),
                            ),
                            Positioned(
                              left: 328.0,
                              top: 698.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 18.0,
                              child: Generated13MilesWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 164.0,
                              height: 36.0,
                              child: GeneratedWFButtonWidget25(),
                            ),
                            Positioned(
                              left: 224.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 164.0,
                              height: 36.0,
                              child: GeneratedWFButtonWidget26(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget36(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
