import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax23widget/generated/GeneratedFrame273Widget13.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax23widget/generated/GeneratedMapsicleMapWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax23widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget35.dart';

/* Frame iPhone 13 Pro Max - 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 64.0,
                              child: GeneratedFrame273Widget13(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 769.0,
                              child: GeneratedMapsicleMapWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget35(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
