import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedWFButtonWidget12.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedFrame758531157Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget11.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedFrame758531158Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedEmojionewavinghandWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedWearehappytoseeyouagainTouseyouraccountyoushouldloginfi.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedWFButtonWidget11.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedCharacterWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedFrame758531155Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedFrame758531156Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax13widget/generated/GeneratedFrame758531258Widget.dart';

/* Frame iPhone 13 Pro Max - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 31.0,
                              child: GeneratedWelcomeBackWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 561.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 36.0,
                              child:
                                  GeneratedWearehappytoseeyouagainTouseyouraccountyoushouldloginfi(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget11(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 787.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 54.0,
                              child: GeneratedWFButtonWidget12(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 676.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 15.0,
                              child: GeneratedFrame758531158Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 615.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 49.0,
                              child: GeneratedFrame758531157Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 32.0,
                              child: GeneratedFrame758531156Widget(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 115.0,
                              right: null,
                              bottom: null,
                              width: 274.0,
                              height: 352.0,
                              child: GeneratedFrame758531155Widget(),
                            ),
                            Positioned(
                              left: 186.0,
                              top: 192.0,
                              right: null,
                              bottom: null,
                              width: 174.0,
                              height: 61.0,
                              child: GeneratedFrame758531258Widget(),
                            ),
                            Positioned(
                              left: 218.0,
                              top: 525.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedEmojionewavinghandWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget11(),
                            ),
                            Positioned(
                              left: 113.159423828125,
                              top: 231.779052734375,
                              right: null,
                              bottom: null,
                              width: 120.53251647949219,
                              height: 234.89952087402344,
                              child: GeneratedCharacterWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
