import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedWFButtonWidget10.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedLineWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedCongratulationsyouraccounthasbeensuccessfullycreatedand.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedLineWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget9.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedGroupWidget20.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedEmojionev1flagforarmeniaWidget3.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedCheckWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedSuccessWidget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax9widget/generated/GeneratedLOGOWidget4.dart';

/* Frame iPhone 13 Pro Max - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 29.0,
                              child: GeneratedLOGOWidget4(),
                            ),
                            Positioned(
                              left: 188.0,
                              top: 364.0,
                              right: null,
                              bottom: null,
                              width: 51.17427444458008,
                              height: 39.97700119018555,
                              child: GeneratedGroupWidget20(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 29.0,
                              child: GeneratedSuccessWidget(),
                            ),
                            Positioned(
                              left: 213.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 2.0,
                              height: 23.0,
                              child: GeneratedTextWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 553.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 60.0,
                              child: GeneratedWFButtonWidget10(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 16.0,
                              child: GeneratedLineWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 390.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 16.0,
                              child: GeneratedLineWidget1(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 317.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedCheckWidget(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 62.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedEmojionev1flagforarmeniaWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 50.0,
                              child:
                                  GeneratedCongratulationsyouraccounthasbeensuccessfullycreatedand(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
