import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFrame38Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedRectangle404Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFilled16pxstarWidget54.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedWFButtonWidget28.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFilled16pxstarWidget53.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFilled16pxstarWidget57.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFrame758531177Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFilled16pxstarWidget56.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFilled16pxstarWidget55.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedFrame138Widget2.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax48widget/generated/GeneratedRectangle405Widget2.dart';

/* Frame iPhone 13 Pro Max - 48
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax48Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 344.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 115.0,
                              child: GeneratedFrame138Widget2(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedFilled16pxstarWidget53(),
                            ),
                            Positioned(
                              left: 158.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedFilled16pxstarWidget54(),
                            ),
                            Positioned(
                              left: 198.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedFilled16pxstarWidget55(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedFilled16pxstarWidget56(),
                            ),
                            Positioned(
                              left: 278.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedFilled16pxstarWidget57(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 174.0,
                              height: 66.0,
                              child: GeneratedFrame758531177Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle404Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 1.0,
                              child: GeneratedRectangle405Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 675.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 56.0,
                              child: GeneratedWFButtonWidget28(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 500.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 155.0,
                              child: GeneratedFrame38Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
