import 'package:flutter/material.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedFrame250Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedFrame758531040Widget6.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedBarsStatusBarsiPhoneLightWidget22.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedFrame758531038Widget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedMay242022Widget.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedTodayWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedYesterdayWidget1.dart';
import 'package:flutterapp/klapmeapp/generatediphone13promax40widget/generated/GeneratedFrame758531039Widget1.dart';

/* Frame iPhone 13 Pro Max - 40
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax40Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 257.0,
                              height: 36.0,
                              child: GeneratedFrame758531038Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 29.0,
                              child: GeneratedTodayWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 180.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame250Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 284.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 29.0,
                              child: GeneratedYesterdayWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame758531039Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 428.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 26.0,
                              child: GeneratedMay242022Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 80.0,
                              child: GeneratedFrame758531040Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 44.0,
                              child:
                                  GeneratedBarsStatusBarsiPhoneLightWidget22(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
